[colors]

  [colors.primary]
    background = '0x1e2127'
    foreground = '0xabb2bf'
    bright_foreground = '0xe6efff'

  # Cursor colors
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  # [colors.cursor]
  #   text = '0x000000'
  #   cursor = '0xffffff'

  [colors.normal]
    black = '0x1e2127'
    red = '0xe06c75'
    green = '0x98c379'
    yellow = '0xd19a66'
    blue = '0x61afef'
    magenta = '0xc678dd'
    cyan = '0x56b6c2'
    white = '0x828791'

  [colors.bright]
    black = '0x5c6370'
    red = '0xe06c75'
    green = '0x98c379'
    yellow = '0xd19a66'
    blue = '0x61afef'
    magenta = '0xc678dd'
    cyan = '0x56b6c2'
    white = '0xe6efff'

  [colors.dim]
    black = '0x1e2127'
    red = '0xe06c75'
    green = '0x98c379'
    yellow = '0xd19a66'
    blue = '0x61afef'
    magenta = '0xc678dd'
    cyan = '0x56b6c2'
    white = '0x828791'

  # Indexed Colors
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  # [[colors.indexed_colors]]
  #   index = 16
  #   color = '0x000000'

[font]
size = 11.0

  [font.bold]
  family = "Berkeley Mono"
  style = "Bold"

  [font.bold_italic]
  family = "Berkeley Mono"
  style = "Bold Italic"

  [font.italic]
  family = "Berkeley Mono"
  style = "Italic"

  [font.normal]
  family = "Berkeley Mono"
  style = "Regular"
